-- ============================================================================
-- Tenant isolation test — Phase A1
--
-- Proves the property from MULTI_TENANT_DESIGN.md §15: logged in as org A you
-- see ZERO rows of org B (and of every other org, including the real one) on
-- every tenant table, and you cannot write into another org.
--
-- HOW TO RUN: paste the whole file into the Supabase SQL editor and run it.
--   * It runs inside BEGIN … ROLLBACK, so it writes nothing: the two test orgs,
--     users and rows are gone when it finishes, pass or fail.
--   * Success  -> the editor shows a table of every check with result 'pass',
--     ending with the row "ALL CHECKS PASSED".
--   * Failure  -> a red error naming the table that leaked, and no result table.
--
-- The Supabase SQL editor renders result sets only and DISCARDS raise notice
-- output, so results are collected in a table and selected at the end rather
-- than announced with notices. (The notices are still emitted for psql/CI.)
--
-- Run it after each of the three A1 migrations is applied, and again after any
-- future change to a policy, a helper function or a tenant table.
-- ============================================================================

begin;

-- Where each passed check is recorded, so the run produces something visible.
-- Created inside the transaction, so the rollback drops it with everything else.
create table public._isolation_results (
  n          int generated by default as identity primary key,
  signed_in  text not null,
  check_name text not null,
  result     text not null default 'pass'
);
-- Supabase enables RLS on tables newly created in public, which would make this
-- scratch table reject its own inserts once we drop to authenticated/anon. It
-- holds no tenant data and disappears with the rollback, so turn it off.
alter table public._isolation_results disable row level security;
grant insert on public._isolation_results to authenticated, anon;

-- Impersonation below only works if the current role is not exempt from RLS.
-- (Table owners and superusers bypass policies, which would make this test
-- pass vacuously; `set role authenticated` is what makes it real.)

-- ---------------------------------------------------------------- seed data
-- Fixed ids so the assertions can be written as literals.

insert into auth.users (id, email) values
  ('aaaaaaaa-0000-4000-8000-000000000001', 'isolation-test-a@example.invalid'),
  ('bbbbbbbb-0000-4000-8000-000000000001', 'isolation-test-b@example.invalid');

insert into public.organizations (id, slug, name) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'isolation-test-a', 'Isolation Test A'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'isolation-test-b', 'Isolation Test B');

insert into public.memberships (org_id, user_id, role) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'aaaaaaaa-0000-4000-8000-000000000001', 'owner'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'bbbbbbbb-0000-4000-8000-000000000001', 'owner');

insert into public.printers (id, org_id, name) values
  ('aaaaaaaa-0000-4000-8000-0000000000f1', 'aaaaaaaa-0000-4000-8000-00000000000a', 'A printer'),
  ('bbbbbbbb-0000-4000-8000-0000000000f1', 'bbbbbbbb-0000-4000-8000-00000000000b', 'B printer');

insert into public.form_entries (org_id, printer_id, first_name, last_name) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'aaaaaaaa-0000-4000-8000-0000000000f1', 'Ada', 'Alpha'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'bbbbbbbb-0000-4000-8000-0000000000f1', 'Ben', 'Bravo');

insert into public.print_jobs (org_id, printer_id, type, status) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'aaaaaaaa-0000-4000-8000-0000000000f1', 'badge', 'queued'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'bbbbbbbb-0000-4000-8000-0000000000f1', 'badge', 'queued');

insert into public.printer_config (org_id) values
  ('aaaaaaaa-0000-4000-8000-00000000000a'),
  ('bbbbbbbb-0000-4000-8000-00000000000b');

insert into public.printer_status (org_id) values
  ('aaaaaaaa-0000-4000-8000-00000000000a'),
  ('bbbbbbbb-0000-4000-8000-00000000000b');

insert into public.app_settings (org_id) values
  ('aaaaaaaa-0000-4000-8000-00000000000a'),
  ('bbbbbbbb-0000-4000-8000-00000000000b');

insert into public.integrations (org_id, kind, enabled, config) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'google_form', true, '{"response_url": "https://a.example/form"}'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'google_form', true, '{"response_url": "https://b.example/form"}');

insert into public.discovered_printers (org_id, ip, model) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', '10.0.0.1', 'Brother QL-820NWB'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', '10.0.0.2', 'Brother QL-820NWB');

insert into public.provisioning_sessions (id, org_id, state, ssid, printer_name) values
  ('aaaaaaaa-0000-4000-8000-0000000000e1', 'aaaaaaaa-0000-4000-8000-00000000000a', 'cable', 'A-WiFi', 'A new printer'),
  ('bbbbbbbb-0000-4000-8000-0000000000e1', 'bbbbbbbb-0000-4000-8000-00000000000b', 'cable', 'B-WiFi', 'B new printer');

insert into public.bridge_tokens (org_id, name, token_hash, token_prefix) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'A bridge', 'hash-a-0000000000000000', 'nbk_aaaa'),
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'B bridge', 'hash-b-0000000000000000', 'nbk_bbbb');

-- Only user B is a platform admin, so user A must not see this table at all
-- and user B must see exactly their own row.
insert into public.platform_admins (user_id)
values ('bbbbbbbb-0000-4000-8000-000000000001');

-- ------------------------------------------------------ checks: as org A user

set local request.jwt.claims = '{"sub":"aaaaaaaa-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  mine  constant uuid := 'aaaaaaaa-0000-4000-8000-00000000000a';
  other constant uuid := 'bbbbbbbb-0000-4000-8000-00000000000b';
  tbl   text;
  n     bigint;
begin
  -- READ isolation on every tenant table. "foreign" counts every row that is
  -- not this org's — org B's *and* any real tenant's — so a policy that leaks
  -- production data fails here too.
  foreach tbl in array array[
    'form_entries', 'print_jobs', 'printers',
    'printer_config', 'printer_status', 'app_settings', 'bridge_tokens',
    'integrations', 'discovered_printers', 'provisioning_sessions'
  ] loop
    execute format('select count(*) from public.%I where org_id <> $1', tbl)
      into n using mine;
    if n <> 0 then
      raise exception 'ISOLATION FAILURE: org A can read % foreign row(s) in %', n, tbl;
    end if;

    execute format('select count(*) from public.%I where org_id = $1', tbl)
      into n using mine;
    if n < 1 then
      raise exception 'TEST BROKEN: org A cannot read its own row in % (RLS too tight, or the seed did not land)', tbl;
    end if;

    insert into public._isolation_results (signed_in, check_name)
    values ('org A owner', format('%s: sees own org only, zero foreign rows', tbl));
  end loop;

  -- The org/membership tables themselves.
  select count(*) into n from public.organizations where id <> mine;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: org A can read % foreign organization row(s)', n;
  end if;
  select count(*) into n from public.organizations where id = mine;
  if n <> 1 then
    raise exception 'TEST BROKEN: org A cannot read its own organization row';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'organizations: sees own org only');

  select count(*) into n from public.memberships where org_id <> mine;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: org A can read % foreign membership(s)', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'memberships: sees own org only');

  -- A is not a platform admin, so the operator list must be invisible.
  select count(*) into n from public.platform_admins;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: a tenant user can read platform_admins (% row(s))', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'platform_admins: invisible to a tenant user');

  -- WRITE isolation: inserting into another org must be refused outright.
  begin
    insert into public.print_jobs (org_id, printer_id, type, status)
    values (other, 'bbbbbbbb-0000-4000-8000-0000000000f1', 'badge', 'queued');
    raise exception 'ISOLATION FAILURE: org A inserted a print_job into org B';
  exception
    when insufficient_privilege then null;  -- expected: RLS WITH CHECK refused it
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'print_jobs: insert into org B refused');

  -- …and an update/delete aimed at another org must simply match nothing.
  update public.printers set name = 'hijacked' where org_id = other;
  get diagnostics n = row_count;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: org A updated % of org B''s printers', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'printers: update aimed at org B matches nothing');

  delete from public.printers where org_id = other;
  get diagnostics n = row_count;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: org A deleted % of org B''s printers', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'printers: delete aimed at org B matches nothing');

  raise notice 'org A: read + write isolation ok';
end;
$$;

-- ------------------------------------------------------ checks: as org B user
-- Symmetric direction, plus the platform-admin read path.

reset role;
set local request.jwt.claims = '{"sub":"bbbbbbbb-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  mine  constant uuid := 'bbbbbbbb-0000-4000-8000-00000000000b';
  tbl   text;
  n     bigint;
begin
  -- B *is* a platform admin, so B legitimately reads across orgs. Isolation for
  -- B is therefore asserted on the tables platform admins get no policy for:
  -- they may read tenant data, but must not gain writes or another org's
  -- membership-derived powers.
  foreach tbl in array array['printers', 'printer_config', 'app_settings'] loop
    execute format(
      'update public.%I set org_id = org_id where org_id <> $1', tbl) using mine;
    get diagnostics n = row_count;
    if n <> 0 then
      raise exception
        'ISOLATION FAILURE: platform admin wrote % foreign row(s) in % (read-only expected)', n, tbl;
    end if;

    insert into public._isolation_results (signed_in, check_name)
    values ('org B owner + platform admin', format('%s: cross-org read grants no writes', tbl));
  end loop;

  -- The platform-admin read policy works, and shows only their own row here.
  select count(*) into n from public.platform_admins;
  if n <> 1 then
    raise exception 'platform_admins should expose exactly the caller''s row, saw %', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org B owner + platform admin', 'platform_admins: sees exactly own row');

  select count(*) into n from public.organizations;
  if n < 2 then
    raise exception 'TEST BROKEN: platform admin should read across orgs, saw % organization(s)', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org B owner + platform admin', 'organizations: cross-org read works');

  -- Membership-scoped writes still apply: B owns org B and may insert there.
  insert into public.print_jobs (org_id, printer_id, type, status)
  values (mine, 'bbbbbbbb-0000-4000-8000-0000000000f1', 'test', 'queued');
  insert into public._isolation_results (signed_in, check_name)
  values ('org B owner + platform admin', 'print_jobs: insert into own org still allowed');

  raise notice 'org B / platform admin: read + write scoping ok';
end;
$$;

-- ------------------------------------- checks: the fleet firmware record
-- Cross-tenant by design: a firmware version belongs to the hardware, not to
-- the congregation. That makes who can read and write it worth pinning down.

reset role;
set local request.jwt.claims = '';

do $$
declare
  row_ public.firmware_observations%rowtype;
begin
  perform public.record_firmware_observation('QL-820NWB', '1.32', true);
  perform public.record_firmware_observation('QL-820NWB', '1.25', false,
            array['set the panel language to English'], 'the printer said no');
  perform public.record_firmware_observation('QL-820NWB', '1.25', false,
            array['set the panel language to English', 'set the power behaviour'], 'again');
  perform public.record_firmware_observation('QL-820NWB', '1.25', true);

  select * into row_ from public.firmware_observations
   where model = 'QL-820NWB' and firmware = '1.25';
  if row_.attempts <> 3 or row_.successes <> 1 or row_.failures <> 2 then
    raise exception 'TEST BROKEN: counted % attempts, % ok, % failed',
      row_.attempts, row_.successes, row_.failures;
  end if;
  -- The actionable part: one step failing consistently is a moved field name.
  if (row_.failed_steps ->> 'set the panel language to English')::int <> 2
     or (row_.failed_steps ->> 'set the power behaviour')::int <> 1 then
    raise exception 'TEST BROKEN: per-step counts are %', row_.failed_steps;
  end if;
  -- A later success must not erase what went wrong before it.
  if row_.last_error is null then
    raise exception 'TEST BROKEN: a success erased the last failure';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('service_role', 'firmware_observations: counts, per-step tallies, last error');
end;
$$;

set local request.jwt.claims = '{"sub":"aaaaaaaa-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  n bigint;
begin
  -- An ordinary org admin sees nothing: it describes every customer's hardware.
  select count(*) into n from public.firmware_observations;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: an org admin can read % firmware row(s)', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'firmware_observations: invisible to a tenant');

  begin
    perform public.record_firmware_observation('QL-820NWB', '9.99', true);
    raise exception 'ISOLATION FAILURE: a tenant wrote to the fleet firmware record';
  exception when insufficient_privilege then null;
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'record_firmware_observation: not callable from the browser');

  begin
    insert into public.firmware_observations (model, firmware) values ('X', '1.0');
    raise exception 'ISOLATION FAILURE: a tenant inserted into the fleet firmware record';
  exception when insufficient_privilege then null;
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'firmware_observations: cannot be written directly');
end;
$$;

-- A platform admin is who this is for.
reset role;
set local request.jwt.claims = '{"sub":"bbbbbbbb-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  n bigint;
begin
  select count(*) into n from public.firmware_observations;
  if n < 2 then
    raise exception 'ISOLATION FAILURE: a platform admin sees only % firmware row(s)', n;
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('platform admin', 'firmware_observations: visible to the platform team');
end;
$$;

reset role;
set local request.jwt.claims = '';

-- --------------------------------- checks: issuing a print-server credential
-- Minting is a platform-team action tied to imaging a card. An organization's
-- own administrators must not be able to do it — not for another org, and not
-- even for their own.

reset role;
set local request.jwt.claims = '{"sub":"aaaaaaaa-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  minted text;
  n bigint;
begin
  -- User A is an owner of org A, and not a platform admin.
  begin
    minted := public.issue_bridge_token('aaaaaaaa-0000-4000-8000-00000000000a', 'Self-issued');
    raise exception
      'ISOLATION FAILURE: an org owner minted a print-server credential (%)', left(minted, 12);
  exception when insufficient_privilege then null;
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'issue_bridge_token: refused to an org owner');

  -- And the direct route is closed too, or the function would be decorative.
  begin
    insert into public.bridge_tokens (org_id, name, token_hash, token_prefix)
    values ('aaaaaaaa-0000-4000-8000-00000000000a', 'Direct', 'hash-direct-00000000', 'nbk_direct');
    raise exception 'ISOLATION FAILURE: an org owner inserted a bridge token directly';
  exception when insufficient_privilege then null;
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'bridge_tokens: cannot be inserted from the browser');
end;
$$;

-- User B is a platform admin, so for them it works — and lands in the org they
-- named, not one of their own.
reset role;
set local request.jwt.claims = '{"sub":"bbbbbbbb-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  minted text;
  n bigint;
begin
  minted := public.issue_bridge_token('aaaaaaaa-0000-4000-8000-00000000000a', 'Lobby Pi');
  if minted is null or left(minted, 4) <> 'nbk_' or length(minted) < 40 then
    raise exception 'TEST BROKEN: issue_bridge_token returned %', coalesce(minted, '(null)');
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('platform admin', 'issue_bridge_token: mints a credential');

  -- Two calls never collide.
  if public.issue_bridge_token('aaaaaaaa-0000-4000-8000-00000000000a')
     = public.issue_bridge_token('aaaaaaaa-0000-4000-8000-00000000000a') then
    raise exception 'ISOLATION FAILURE: issue_bridge_token returned the same secret twice';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('platform admin', 'issue_bridge_token: a fresh secret each time');

  -- Not even a platform admin can read a hash back: token_hash is outside the
  -- SELECT grant entirely, so this must fail rather than return a row.
  begin
    select count(*) into n from public.bridge_tokens where token_hash is not null;
    raise exception 'ISOLATION FAILURE: token_hash is readable from a signed-in session';
  exception when insufficient_privilege then null;
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('platform admin', 'bridge_tokens: token_hash is not readable at all');

  -- Stash it for the server-side check below, which needs superuser to see
  -- the column.
  create temporary table _minted (secret text) on commit drop;
  insert into _minted values (minted);
end;
$$;

reset role;
set local request.jwt.claims = '';

do $$
declare
  minted text;
  n bigint;
begin
  select secret into minted from _minted;

  -- The plaintext must not be recoverable from what was stored.
  select count(*) into n from public.bridge_tokens where token_hash = minted;
  if n <> 0 then
    raise exception 'ISOLATION FAILURE: the credential was stored in the clear';
  end if;
  select count(*) into n from public.bridge_tokens
   where token_hash = encode(sha256(convert_to(minted, 'utf8')), 'hex')
     and org_id = 'aaaaaaaa-0000-4000-8000-00000000000a';
  if n <> 1 then
    raise exception 'TEST BROKEN: the hash was not stored against the named org';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('—', 'issue_bridge_token: stores only the hash, against the named org');
end;
$$;

-- ------------------------------------- checks: provisioning secrets (B3)
-- The WiFi passphrase an operator types during provisioning is the customer's,
-- and provisioning_secret() hands back a decrypted one for whatever session id
-- it is given. If a signed-in user can call it, every organization's WiFi
-- password is one function call away.

-- Stash a passphrase on each org's session, the way the admin UI does — as
-- that org's own administrator, which is the only way it can be done.
set local request.jwt.claims = '{"sub":"aaaaaaaa-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;
select public.set_provisioning_secret(
  'aaaaaaaa-0000-4000-8000-0000000000e1', 'wifi_passphrase', 'a-secret-passphrase');

reset role;
set local request.jwt.claims = '{"sub":"bbbbbbbb-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;
select public.set_provisioning_secret(
  'bbbbbbbb-0000-4000-8000-0000000000e1', 'wifi_passphrase', 'b-secret-passphrase');

reset role;
set local request.jwt.claims = '';

do $$
begin
  -- The server path still works, or the bridge could never provision anything.
  if public.provisioning_secret(
       'aaaaaaaa-0000-4000-8000-0000000000e1', 'wifi_passphrase')
     <> 'a-secret-passphrase' then
    raise exception 'TEST BROKEN: the server cannot read a provisioning secret';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('service_role', 'provisioning_secret: the bridge path still works');
end;
$$;

set local request.jwt.claims = '{"sub":"aaaaaaaa-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  leaked text;
begin
  -- Not their own, and not anyone else's.
  begin
    leaked := public.provisioning_secret(
      'bbbbbbbb-0000-4000-8000-0000000000e1', 'wifi_passphrase');
    raise exception
      'ISOLATION FAILURE: a signed-in user decrypted another org''s WiFi passphrase (%)',
      leaked;
  exception
    when insufficient_privilege then null;  -- no EXECUTE: correct
  end;

  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'provisioning_secret: not callable from the browser');

  -- Cross-org read of the session row itself.
  if exists (select 1 from public.provisioning_sessions
              where org_id = 'bbbbbbbb-0000-4000-8000-00000000000b') then
    raise exception 'ISOLATION FAILURE: org A can see org B''s provisioning session';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'provisioning_sessions: another org''s session is invisible');

  -- Setting a secret on someone else's session is refused too.
  begin
    perform public.set_provisioning_secret(
      'bbbbbbbb-0000-4000-8000-0000000000e1', 'wifi_passphrase', 'hijacked');
    raise exception
      'ISOLATION FAILURE: org A wrote a secret onto org B''s provisioning session';
  exception
    when insufficient_privilege then null;
  end;
  insert into public._isolation_results (signed_in, check_name)
  values ('org A owner', 'set_provisioning_secret: refused for another org');
end;
$$;

reset role;

-- Deleting a session must take its Vault entries with it, or an abandoned
-- setup would leave the customer's WiFi password behind indefinitely.
do $$
declare
  v_id uuid;
  n    bigint;
begin
  select nullif(secrets ->> 'wifi_passphrase', '')::uuid into v_id
    from public.provisioning_sessions
   where id = 'aaaaaaaa-0000-4000-8000-0000000000e1';
  if v_id is null then
    raise exception 'TEST BROKEN: no vault id recorded on the session';
  end if;

  delete from public.provisioning_sessions
   where id = 'aaaaaaaa-0000-4000-8000-0000000000e1';

  select count(*) into n from vault.secrets where id = v_id;
  if n <> 0 then
    raise exception
      'ISOLATION FAILURE: a deleted provisioning session left its passphrase in Vault';
  end if;
  insert into public._isolation_results (signed_in, check_name)
  values ('—', 'provisioning secrets: deleted with the session');
end;
$$;

-- --------------------------------------------------------- checks: as anon
-- The public sign-in form uses the anon key; it must reach nothing directly.

reset role;
set local request.jwt.claims = '';
set local role anon;

do $$
declare
  tbl text;
  n   bigint;
begin
  foreach tbl in array array[
    'form_entries', 'print_jobs', 'printers', 'printer_config',
    'printer_status', 'app_settings', 'organizations', 'memberships',
    'platform_admins', 'bridge_tokens', 'integrations', 'discovered_printers',
    'provisioning_sessions'
  ] loop
    begin
      execute format('select count(*) from public.%I', tbl) into n;
      if n <> 0 then
        raise exception 'ISOLATION FAILURE: anon can read % row(s) of %', n, tbl;
      end if;
    exception
      when insufficient_privilege then null;  -- no grant at all: even better
    end;

    insert into public._isolation_results (signed_in, check_name)
    values ('anon (public form)', format('%s: no direct access', tbl));
  end loop;

  raise notice 'anon: no table access ok';
end;
$$;

reset role;

insert into public._isolation_results (signed_in, check_name)
values ('—', 'ALL CHECKS PASSED');

do $$
begin
  raise notice 'TENANT ISOLATION: ALL CHECKS PASSED';
end;
$$;

-- The result the SQL editor displays: one row per check, all 'pass', ending
-- with ALL CHECKS PASSED. Any failure aborts before this with a red error.
select n, signed_in, check_name, result
from public._isolation_results
order by n;

rollback;
