-- ============================================================================
-- Operator role test
--
-- Proves the line drawn in the operators migration: an owner may do the
-- irreversible and may change who has access; a support operator may do
-- everything else. A permission column nothing enforces is worse than no
-- column, so this is the file that stops that happening.
--
-- HOW TO RUN: paste the whole file into the Supabase SQL editor and run it.
--   * Runs inside BEGIN … ROLLBACK — it writes nothing, pass or fail.
--   * Success -> a table of every check, all 'pass', ending ALL CHECKS PASSED.
--   * Failure -> a red error naming the capability that was wrong.
--
-- It empties platform_admins inside the transaction. That is deliberate: the
-- last-owner guards count owners across the whole table, so they cannot be
-- tested while the real operators are still in it. The rollback puts them
-- back — as it does for everything else this file touches.
-- ============================================================================

begin;

create table public._op_results (
  n          int generated by default as identity primary key,
  acting_as  text not null,
  check_name text not null,
  result     text not null default 'pass'
);
-- Supabase enables RLS on tables newly created in public; this scratch table
-- holds no tenant data and dies with the rollback.
alter table public._op_results disable row level security;
grant insert on public._op_results to authenticated;

-- ---------------------------------------------------------------- seed data

insert into auth.users (id, email) values
  ('0c0c0000-0000-4000-8000-000000000001', 'op-test-owner@example.invalid'),
  ('0c0c0000-0000-4000-8000-000000000002', 'op-test-support@example.invalid'),
  ('0c0c0000-0000-4000-8000-000000000003', 'op-test-nobody@example.invalid');

insert into public.organizations (id, slug, name) values
  ('0c0c0000-0000-4000-8000-00000000000a', 'op-test-victim', 'Operator Test Victim');

-- See the header: the real operators are removed for the duration so that the
-- global owner counts are the test's own.
delete from public.platform_admins;
insert into public.platform_admins (user_id, role) values
  ('0c0c0000-0000-4000-8000-000000000001', 'owner'),
  ('0c0c0000-0000-4000-8000-000000000002', 'support');

-- ---------------------------------------------------------- acting as SUPPORT

set local request.jwt.claims = '{"sub":"0c0c0000-0000-4000-8000-000000000002","role":"authenticated"}';
set local role authenticated;

do $$
declare
  victim constant uuid := '0c0c0000-0000-4000-8000-00000000000a';
  fresh uuid;
  n bigint;
begin
  if not public.is_platform_admin() then
    raise exception 'TEST BROKEN: expected to be acting as an operator';
  end if;
  if public.is_platform_owner() then
    raise exception 'ROLE FAILURE: a support operator reports as an owner';
  end if;
  insert into public._op_results (acting_as, check_name) values ('support', 'is an operator, not an owner');

  -- Can see the whole team …
  select count(*) into n from public.list_operators();
  if n <> 2 then raise exception 'ROLE FAILURE: support sees % operators, expected 2', n; end if;
  insert into public._op_results (acting_as, check_name) values ('support', 'sees the operator list');

  -- … while the table itself still yields only their own row. list_operators()
  -- must be the only way in, or the read policy has quietly stopped mattering.
  select count(*) into n from public.platform_admins;
  if n <> 1 then
    raise exception 'ROLE FAILURE: platform_admins returned % rows directly, expected 1', n;
  end if;
  insert into public._op_results (acting_as, check_name) values ('support', 'table still shows only their own row');

  -- Can onboard a customer …
  fresh := public.create_organization('op-test-new', 'Operator Test New');
  insert into public._op_results (acting_as, check_name) values ('support', 'can create an organization');

  -- … and do the reversible thing to it. Note *which* org: creating one makes
  -- the creator its owner, and that membership is what the update policy on
  -- organizations actually consults. The platform-admin policies are all
  -- `for select`, so an operator has no cross-tenant write at all today —
  -- suspending a customer works only where the operator happens to be a
  -- member. That coupling is what the auth_org_ids() widening removes; until
  -- then this check has to use an org support just created.
  update public.organizations set status = 'suspended' where id = fresh;
  if (select status from public.organizations where id = fresh) <> 'suspended' then
    raise exception 'ROLE FAILURE: support could not suspend an organization it owns';
  end if;
  update public.organizations set status = 'active' where id = fresh;
  insert into public._op_results (acting_as, check_name) values ('support', 'can suspend and resume');

  -- And an org it is not a member of, which is the whole point of an operator.
  -- This assertion used to say the opposite, as a tripwire for the change that
  -- has now happened: operators reach every organization with owner-equivalent
  -- access, so support suspending a tenant it never joined is correct.
  update public.organizations set status = 'suspended' where id = victim;
  if (select status from public.organizations where id = victim) <> 'suspended' then
    raise exception 'ROLE FAILURE: support could not suspend an org it is not a member of';
  end if;
  update public.organizations set status = 'active' where id = victim;
  insert into public._op_results (acting_as, check_name)
    values ('support', 'acts in an org it does not belong to');

  -- Owner-equivalent inside a tenant, but the platform role still governs
  -- platform actions — which is why the delete check further down still
  -- refuses. Reaching into an organization is not the same as destroying it.
  if public.auth_org_role(victim) <> 'owner' then
    raise exception 'ROLE FAILURE: support is % in a foreign org, expected owner',
      public.auth_org_role(victim);
  end if;
  insert into public._op_results (acting_as, check_name)
    values ('support', 'is owner-equivalent inside any org');

  -- But not the irreversible one.
  begin
    perform public.delete_organization(victim, 'op-test-victim');
    raise exception 'ROLE FAILURE: a support operator deleted an organization';
  exception when insufficient_privilege then null;
  end;
  insert into public._op_results (acting_as, check_name) values ('support', 'cannot delete an organization');

  -- And not who else gets in.
  begin
    perform public.remove_operator('0c0c0000-0000-4000-8000-000000000001');
    raise exception 'ROLE FAILURE: a support operator removed an operator';
  exception when insufficient_privilege then null;
  end;
  begin
    perform public.set_operator_role('0c0c0000-0000-4000-8000-000000000001', 'support');
    raise exception 'ROLE FAILURE: a support operator demoted an owner';
  exception when insufficient_privilege then null;
  end;
  insert into public._op_results (acting_as, check_name) values ('support', 'cannot add, remove or re-role an operator');
end;
$$;

reset role;

-- ----------------------------------------------------------- acting as NOBODY

set local request.jwt.claims = '{"sub":"0c0c0000-0000-4000-8000-000000000003","role":"authenticated"}';
set local role authenticated;

do $$
declare
  n bigint;
begin
  if public.is_platform_admin() then
    raise exception 'TEST BROKEN: expected to be acting as a non-operator';
  end if;

  -- The check is in the WHERE clause, per row, so this is empty rather than an
  -- error — and empty is what stops it becoming a list of who to attack.
  select count(*) into n from public.list_operators();
  if n <> 0 then raise exception 'ROLE FAILURE: a non-operator saw % operators', n; end if;

  select count(*) into n from public.platform_admins;
  if n <> 0 then raise exception 'ROLE FAILURE: a non-operator read % platform_admins rows', n; end if;
  insert into public._op_results (acting_as, check_name) values ('nobody', 'sees no operators at all');
end;
$$;

reset role;

-- ------------------------------------------------------------ acting as OWNER

set local request.jwt.claims = '{"sub":"0c0c0000-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  owner   constant uuid := '0c0c0000-0000-4000-8000-000000000001';
  support constant uuid := '0c0c0000-0000-4000-8000-000000000002';
  victim  constant uuid := '0c0c0000-0000-4000-8000-00000000000a';
  gone jsonb;
begin
  if not public.is_platform_owner() then
    raise exception 'TEST BROKEN: expected to be acting as an owner';
  end if;

  -- Promotion and demotion both work while another owner exists.
  perform public.set_operator_role(support, 'owner');
  if (select role from public.platform_admins where user_id = support) <> 'owner' then
    raise exception 'ROLE FAILURE: an owner could not promote a support operator';
  end if;
  perform public.set_operator_role(support, 'support');
  insert into public._op_results (acting_as, check_name) values ('owner', 'can promote and demote');

  -- The lockout guards. With one owner left, neither route may take the last.
  --
  -- These assertions deliberately avoid the words the guard itself uses. The
  -- handler recognises the guard by its message, so a failure message
  -- containing the same phrase would be caught as if it were the refusal —
  -- the check would then pass in exactly the case it exists to catch.
  begin
    perform public.set_operator_role(owner, 'support');
    raise exception 'ROLE FAILURE: the sole owner demoted themselves';
  exception when raise_exception then
    if position('last owner' in sqlerrm) = 0 then raise; end if;
  end;
  begin
    perform public.remove_operator(owner);
    raise exception 'ROLE FAILURE: the sole owner removed themselves';
  exception when raise_exception then
    if position('last owner' in sqlerrm) = 0 then raise; end if;
  end;
  insert into public._op_results (acting_as, check_name) values ('owner', 'cannot take the last owner');

  -- Stepping someone else down is fine, and is how an operator leaves.
  perform public.remove_operator(support);
  if exists (select 1 from public.platform_admins where user_id = support) then
    raise exception 'ROLE FAILURE: remove_operator left the row in place';
  end if;
  insert into public._op_results (acting_as, check_name) values ('owner', 'can remove another operator');

  -- And the irreversible thing an owner is for.
  gone := public.delete_organization(victim, 'op-test-victim');
  if gone->>'slug' <> 'op-test-victim' then
    raise exception 'ROLE FAILURE: delete_organization returned %', gone;
  end if;
  if exists (select 1 from public.organizations where id = victim) then
    raise exception 'ROLE FAILURE: the organization survived its own deletion';
  end if;
  insert into public._op_results (acting_as, check_name) values ('owner', 'can delete an organization');
end;
$$;

reset role;

-- Outside the role blocks: auth.users is not reachable from the Data API at
-- all, which is why org_members() and list_operators() are SECURITY DEFINER.
do $$
begin
  if not exists (select 1 from auth.users where id = '0c0c0000-0000-4000-8000-000000000002') then
    raise exception 'ROLE FAILURE: removing an operator deleted their account';
  end if;
  insert into public._op_results (acting_as, check_name)
    values ('—', 'a removed operator keeps their account');
end;
$$;

insert into public._op_results (acting_as, check_name) values ('—', 'ALL CHECKS PASSED');

select n, acting_as, check_name, result from public._op_results order by n;

rollback;
