-- ============================================================================
-- Role matrix test — Phase A2
--
-- Proves the capability table in MULTI_TENANT_DESIGN.md §5: staff can run the
-- kiosk but not change it, admins can change it but cannot touch owners, owners
-- can do everything except leave the org without an owner.
--
-- HOW TO RUN: paste the whole file into the Supabase SQL editor and run it.
--   * Runs inside BEGIN … ROLLBACK — it writes nothing, pass or fail.
--   * Success -> a table of every check, all 'pass', ending ALL CHECKS PASSED.
--   * Failure -> a red error naming the capability that was wrong.
--
-- Two different refusal shapes are asserted, and the difference matters:
--   * INSERT against a WITH CHECK is REFUSED (error 42501).
--   * UPDATE/DELETE against a USING clause simply MATCHES NOTHING (0 rows),
--     because a row the caller may not touch is invisible to the statement.
-- ============================================================================

begin;

create table public._role_results (
  n          int generated by default as identity primary key,
  acting_as  text not null,
  check_name text not null,
  result     text not null default 'pass'
);
-- Supabase enables RLS on tables newly created in public; this scratch table
-- holds no tenant data and dies with the rollback.
alter table public._role_results disable row level security;
grant insert on public._role_results to authenticated;

-- ---------------------------------------------------------------- seed data

insert into auth.users (id, email) values
  ('0a2a0000-0000-4000-8000-000000000001', 'role-test-owner@example.invalid'),
  ('0a2a0000-0000-4000-8000-000000000002', 'role-test-admin@example.invalid'),
  ('0a2a0000-0000-4000-8000-000000000003', 'role-test-staff@example.invalid');

insert into public.organizations (id, slug, name) values
  ('0a2a0000-0000-4000-8000-00000000000a', 'role-test-org',   'Role Test Org'),
  ('0a2b0000-0000-4000-8000-00000000000b', 'role-test-other', 'Role Test Other Org');

insert into public.memberships (org_id, user_id, role) values
  ('0a2a0000-0000-4000-8000-00000000000a', '0a2a0000-0000-4000-8000-000000000001', 'owner'),
  ('0a2a0000-0000-4000-8000-00000000000a', '0a2a0000-0000-4000-8000-000000000002', 'admin'),
  ('0a2a0000-0000-4000-8000-00000000000a', '0a2a0000-0000-4000-8000-000000000003', 'staff');

insert into public.printers (id, org_id, name) values
  ('0a2a0000-0000-4000-8000-0000000000f1', '0a2a0000-0000-4000-8000-00000000000a', 'Role Test Printer');

insert into public.form_entries (org_id, printer_id, first_name, last_name) values
  ('0a2a0000-0000-4000-8000-00000000000a', '0a2a0000-0000-4000-8000-0000000000f1', 'Rosa', 'Roletest');

insert into public.printer_config (org_id) values ('0a2a0000-0000-4000-8000-00000000000a');
insert into public.printer_status (org_id) values ('0a2a0000-0000-4000-8000-00000000000a');
insert into public.app_settings   (org_id) values ('0a2a0000-0000-4000-8000-00000000000a');

-- A print server, so the checks below count something that is actually there.
-- Without it "staff sees 0 bridge tokens" passes against an empty table and
-- proves nothing. Minting now goes through issue_bridge_token(), which only a
-- platform admin may call, so the row is seeded directly here.
insert into public.bridge_tokens (org_id, name, token_hash, token_prefix)
values ('0a2a0000-0000-4000-8000-00000000000a', 'Lobby Pi',
        'hash-seeded-0000000000', 'nbk_seeded');

-- A setup in progress, so the staff checks below are counting something that
-- is actually there. Seeded before any role is assumed, as the owner.
insert into public.provisioning_sessions (id, org_id, state, printer_name, ssid)
values ('0a2a0000-0000-4000-8000-0000000000e1', '0a2a0000-0000-4000-8000-00000000000a',
        'cable', 'Role test printer', 'Role-WiFi');

-- ------------------------------------------------------------ acting as STAFF

set local request.jwt.claims = '{"sub":"0a2a0000-0000-4000-8000-000000000003","role":"authenticated"}';
set local role authenticated;

do $$
declare
  org      constant uuid := '0a2a0000-0000-4000-8000-00000000000a';
  printer  constant uuid := '0a2a0000-0000-4000-8000-0000000000f1';
  n bigint;
begin
  if public.auth_org_role(org) <> 'staff' then
    raise exception 'TEST BROKEN: expected to be acting as staff, got %', public.auth_org_role(org);
  end if;

  -- Can do the job: see the org's data …
  select count(*) into n from public.form_entries where org_id = org;
  if n < 1 then raise exception 'ROLE FAILURE: staff cannot read form_entries'; end if;
  insert into public._role_results (acting_as, check_name) values ('staff', 'reads entries');

  -- … and reprint / test-print.
  insert into public.print_jobs (org_id, printer_id, type, status)
  values (org, printer, 'badge', 'queued');
  insert into public.print_jobs (org_id, printer_id, type, status)
  values (org, printer, 'test', 'queued');
  insert into public._role_results (acting_as, check_name) values ('staff', 'can reprint and test-print');

  -- Cannot change the setup: adding a printer is refused outright.
  begin
    insert into public.printers (org_id, name) values (org, 'Staff Printer');
    raise exception 'ROLE FAILURE: staff added a printer';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name) values ('staff', 'cannot add a printer');

  -- Editing or deleting one matches nothing.
  update public.printers set name = 'renamed by staff' where org_id = org;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: staff renamed % printer(s)', n; end if;
  delete from public.printers where org_id = org;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: staff deleted % printer(s)', n; end if;
  insert into public._role_results (acting_as, check_name) values ('staff', 'cannot edit or delete printers');

  update public.app_settings set selfie_mode = 'required' where org_id = org;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: staff changed app_settings'; end if;
  update public.printer_config set label_media = '29' where org_id = org;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: staff changed printer_config'; end if;
  insert into public._role_results (acting_as, check_name) values ('staff', 'cannot change settings or printer config');

  -- Reads the printers, and only the printers. The Print Server tab shows
  -- per-printer state — ready, unreachable, what media is loaded — which is
  -- the question a greeter at a sign-in table actually has. The Printers and
  -- Settings tabs are an admin's, so the rows behind them are too.
  select count(*) into n from public.printers where org_id = org;
  if n < 1 then raise exception 'ROLE FAILURE: staff cannot see the printers'; end if;
  select count(*) into n from public.printer_config where org_id = org;
  if n <> 0 then raise exception 'ROLE FAILURE: staff read % printer_config row(s)', n; end if;
  select count(*) into n from public.app_settings where org_id = org;
  if n <> 0 then raise exception 'ROLE FAILURE: staff read % app_settings row(s)', n; end if;
  insert into public._role_results (acting_as, check_name)
    values ('staff', 'reads printers but not config or settings');

  -- Integrations and API keys are not staff business at all.
  select count(*) into n from public.api_keys where org_id = org;
  if n <> 0 then raise exception 'ROLE FAILURE: staff read % API key(s)', n; end if;
  insert into public._role_results (acting_as, check_name) values ('staff', 'sees no API keys');

  -- Who did what is the owner's business, not the desk's.
  select count(*) into n from public.activity_log where org_id = org;
  if n <> 0 then raise exception 'ROLE FAILURE: staff read % activity row(s)', n; end if;
  insert into public._role_results (acting_as, check_name) values ('staff', 'sees no activity log');

  -- Device credentials are not staff business: invisible, and uncreatable.
  select count(*) into n from public.bridge_tokens where org_id = org;
  if n <> 0 then
    raise exception 'ROLE FAILURE: staff can see % bridge token(s)', n;
  end if;
  begin
    insert into public.bridge_tokens (org_id, name, token_hash)
    values (org, 'Staff bridge', 'hash-staff-000000000000');
    raise exception 'ROLE FAILURE: staff created a bridge token';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('staff', 'cannot see or create bridge tokens');

  -- Provisioning carries the site's WiFi credentials and reconfigures hardware,
  -- so it is out of scope for staff entirely — they cannot see one, start one,
  -- or push one along.
  select count(*) into n from public.provisioning_sessions where org_id = org;
  if n <> 0 then
    raise exception 'ROLE FAILURE: staff can see % provisioning session(s)', n;
  end if;
  begin
    insert into public.provisioning_sessions (org_id, state, printer_name)
    values (org, 'reset', 'Staff printer');
    raise exception 'ROLE FAILURE: staff started a provisioning session';
  exception when insufficient_privilege then null;
  end;
  update public.provisioning_sessions set state = 'discover'
   where id = '0a2a0000-0000-4000-8000-0000000000e1';
  get diagnostics n = row_count;
  if n <> 0 then
    raise exception 'ROLE FAILURE: staff advanced a provisioning session';
  end if;
  begin
    perform public.set_provisioning_secret(
      '0a2a0000-0000-4000-8000-0000000000e1', 'wifi_passphrase', 'staff-should-not-set-this');
    raise exception 'ROLE FAILURE: staff set a provisioning secret';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('staff', 'cannot see, start, or advance a printer setup');

  -- Suspension is the platform's lever, so an org must not be able to lift it.
  -- Same shape of hole as custom_integrations: A2's update policy is
  -- column-blind, and one boolean would put a suspended customer back in
  -- service.
  update public.organizations set status = 'active' where id = org;
  get diagnostics n = row_count;
  if n <> 0 then
    raise exception 'ROLE FAILURE: staff changed the organization status';
  end if;
  insert into public._role_results (acting_as, check_name)
  values ('staff', 'cannot change the organization status');

  -- Custom integrations are sold and switched on by us. An org must not be
  -- able to grant itself a paid capability, and A2 gave owners a column-blind
  -- update on their own organizations row — so this is worth pinning down.
  update public.organizations set custom_integrations = true where id = org;
  get diagnostics n = row_count;
  if n <> 0 then
    raise exception 'ROLE FAILURE: staff enabled custom integrations';
  end if;
  insert into public._role_results (acting_as, check_name)
  values ('staff', 'cannot enable custom integrations');

  -- Integration settings are an admin concern, not a staff one.
  select count(*) into n from public.integrations where org_id = org;
  if n <> 0 then
    raise exception 'ROLE FAILURE: staff can see % integration row(s)', n;
  end if;
  begin
    perform public.set_integration_secret(org, 'google_drive', 'staff-should-not-manage-this');
    raise exception 'ROLE FAILURE: staff set an integration credential';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('staff', 'cannot see or configure integrations');

  -- Cannot add members.
  begin
    insert into public.memberships (org_id, user_id, role)
    values (org, '0a2a0000-0000-4000-8000-000000000001', 'staff');
    raise exception 'ROLE FAILURE: staff added a membership';
  exception when insufficient_privilege then null;
       when unique_violation then
         raise exception 'TEST BROKEN: membership already existed, cannot judge the policy';
  end;
  insert into public._role_results (acting_as, check_name) values ('staff', 'cannot add members');
end;
$$;

-- ------------------------------------------------------------ acting as ADMIN

reset role;
set local request.jwt.claims = '{"sub":"0a2a0000-0000-4000-8000-000000000002","role":"authenticated"}';
set local role authenticated;

do $$
declare
  org     constant uuid := '0a2a0000-0000-4000-8000-00000000000a';
  ownerid constant uuid := '0a2a0000-0000-4000-8000-000000000001';
  staffid constant uuid := '0a2a0000-0000-4000-8000-000000000003';
  n bigint;
begin
  if public.auth_org_role(org) <> 'admin' then
    raise exception 'TEST BROKEN: expected to be acting as admin, got %', public.auth_org_role(org);
  end if;

  -- Runs the setup.
  insert into public.printers (org_id, name) values (org, 'Admin Printer');
  update public.printers set name = 'renamed by admin' where org_id = org and name = 'Admin Printer';
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: admin could not rename a printer'; end if;
  insert into public._role_results (acting_as, check_name) values ('admin', 'manages printers');

  update public.app_settings set selfie_mode = 'optional' where org_id = org;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: admin could not change app_settings'; end if;
  update public.printer_config set label_media = '29' where org_id = org;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: admin could not change printer_config'; end if;
  insert into public._role_results (acting_as, check_name) values ('admin', 'changes settings and printer config');

  -- Manages nobody. Access is granted by the people who own the account, not
  -- by whoever runs the desk equipment — so an admin cannot touch a
  -- membership of any role, including staff.
  update public.memberships set role = 'staff' where org_id = org and user_id = staffid;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: admin changed % staff membership(s)', n; end if;
  delete from public.memberships where org_id = org and user_id = staffid;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: admin removed % staff membership(s)', n; end if;

  begin
    insert into public.memberships (org_id, user_id, role)
    values (org, '0a2b0000-0000-4000-8000-00000000000b', 'staff');
    raise exception 'ROLE FAILURE: admin added a member';
  exception when insufficient_privilege then null;
       when foreign_key_violation then
         raise exception 'TEST BROKEN: the policy allowed the insert (it failed on the FK instead)';
  end;
  insert into public._role_results (acting_as, check_name) values ('admin', 'manages no members at all');

  -- Cannot touch an owner either, for the same reason rather than a special one.
  update public.memberships set role = 'staff' where org_id = org and user_id = ownerid;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: admin demoted an owner'; end if;
  insert into public._role_results (acting_as, check_name) values ('admin', 'cannot demote or remove an owner');

  -- Integrations and API keys moved to the owner: both hand out a way in.
  select count(*) into n from public.api_keys where org_id = org;
  if n <> 0 then raise exception 'ROLE FAILURE: admin read % API key(s)', n; end if;
  begin
    insert into public.api_keys (org_id, name, key_hash, key_prefix)
    values (org, 'admin key', 'hash-admin-000000', 'nbk_adm');
    raise exception 'ROLE FAILURE: admin minted an API key';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name) values ('admin', 'cannot see or mint API keys');

  -- Cannot rename the organization.
  update public.organizations set name = 'Renamed by admin' where id = org;
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: admin renamed the organization'; end if;
  insert into public._role_results (acting_as, check_name) values ('admin', 'cannot rename the organization');

  -- Sees the org's print servers, and can stop one …
  select count(*) into n from public.bridge_tokens where org_id = org;
  if n <> 1 then raise exception 'ROLE FAILURE: admin sees % bridge tokens, expected 1', n; end if;
  update public.bridge_tokens set revoked_at = now() where org_id = org;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: admin could not revoke a bridge token'; end if;
  update public.bridge_tokens set revoked_at = null where org_id = org;
  insert into public._role_results (acting_as, check_name)
  values ('admin', 'lists and revokes bridge tokens');

  -- … but does not mint one. A print server's credential is written when the
  -- card is imaged and replaced by the device itself; an administrator who
  -- could mint one would only get a secret they cannot install.
  begin
    perform public.issue_bridge_token(org, 'Self-issued');
    raise exception 'ROLE FAILURE: an admin minted a print-server credential';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('admin', 'cannot mint a print-server credential');

  -- … but never gets the stored hash back out of the database.
  begin
    perform token_hash from public.bridge_tokens where org_id = org;
    raise exception 'ROLE FAILURE: token_hash is readable through the Data API';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('admin', 'cannot read token_hash');

  -- Integrations belong to the owner now, and the boundary has to hold on
  -- both routes: the table, and the SECURITY DEFINER helpers that write into
  -- the Vault behind it.
  begin
    insert into public.integrations (org_id, kind, enabled, config)
    values (org, 'google_form', true, '{"response_url": "https://example.invalid/form"}');
    raise exception 'ROLE FAILURE: admin configured an integration';
  exception when insufficient_privilege then null;
  end;
  begin
    perform public.set_integration_secret(org, 'google_drive', 'a-fake-private-key');
    raise exception 'ROLE FAILURE: admin stored an integration credential';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('admin', 'cannot configure integrations or store a credential');

  begin
    perform secret_id from public.integrations where org_id = org;
    raise exception 'ROLE FAILURE: secret_id is readable through the Data API';
  exception when insufficient_privilege then null;
  end;
  begin
    perform public.integration_for(org, 'google_drive');
    raise exception 'ROLE FAILURE: an admin can decrypt an integration credential';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('admin', 'cannot read a stored credential back');

  -- And cannot configure a different organization.
  begin
    perform public.set_integration_secret(
      '0a2b0000-0000-4000-8000-00000000000b'::uuid, 'google_drive', 'not-mine');
    raise exception 'ISOLATION FAILURE: admin configured another org''s integration';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('admin', 'cannot configure another org''s integration');

  -- Sees the member list for its own org, and nothing for a foreign one.
  select count(*) into n from public.org_members(org);
  if n <> 3 then raise exception 'ROLE FAILURE: org_members returned % rows, expected 3', n; end if;
  select count(*) into n from public.org_members('0a2b0000-0000-4000-8000-00000000000b');
  if n <> 0 then raise exception 'ISOLATION FAILURE: org_members leaked % row(s) of another org', n; end if;
  insert into public._role_results (acting_as, check_name) values ('admin', 'org_members: own org only');
end;
$$;

-- ------------------------------------------------------------ acting as OWNER

reset role;
set local request.jwt.claims = '{"sub":"0a2a0000-0000-4000-8000-000000000001","role":"authenticated"}';
set local role authenticated;

do $$
declare
  org     constant uuid := '0a2a0000-0000-4000-8000-00000000000a';
  adminid constant uuid := '0a2a0000-0000-4000-8000-000000000002';
  n bigint;
begin
  if public.auth_org_role(org) <> 'owner' then
    raise exception 'TEST BROKEN: expected to be acting as owner, got %', public.auth_org_role(org);
  end if;

  update public.organizations set name = 'Renamed by owner' where id = org;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: owner could not rename the organization'; end if;
  insert into public._role_results (acting_as, check_name) values ('owner', 'renames the organization');

  -- The capability the admin was just refused has to land somewhere, or a
  -- suite made only of refusals passes with the feature entirely broken.
  insert into public.integrations (org_id, kind, enabled, config)
  values (org, 'google_form', true, '{"response_url": "https://example.invalid/form"}');
  perform public.set_integration_secret(org, 'google_drive', 'a-fake-private-key');
  if not public.integration_has_secret(org, 'google_drive') then
    raise exception 'ROLE FAILURE: owner could not store an integration credential';
  end if;
  insert into public._role_results (acting_as, check_name)
  values ('owner', 'configures integrations and stores a credential');

  -- … and still cannot read the credential back. Owning the integration is not
  -- the same as being able to extract what is inside it.
  begin
    perform secret_id from public.integrations where org_id = org;
    raise exception 'ROLE FAILURE: secret_id is readable through the Data API';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('owner', 'cannot read a stored credential back');

  -- API keys moved with them.
  insert into public.api_keys (org_id, name, key_hash, key_prefix)
  values (org, 'owner key', 'hash-owner-000000', 'nbk_own');
  select count(*) into n from public.api_keys where org_id = org;
  if n <> 1 then raise exception 'ROLE FAILURE: owner sees % API key(s), expected 1', n; end if;
  insert into public._role_results (acting_as, check_name) values ('owner', 'mints and sees API keys');

  -- The same row, a different column. A2's update policy cannot tell them
  -- apart, so if the trigger is missing this succeeds and an org helps itself
  -- to a capability we charge for.
  begin
    update public.organizations set custom_integrations = true where id = org;
    raise exception 'ROLE FAILURE: an owner enabled custom integrations for their own org';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('owner', 'cannot enable custom integrations');

  -- The one that has teeth: an owner who could clear their own suspension
  -- could ignore it entirely.
  begin
    update public.organizations set status = 'suspended' where id = org;
    raise exception 'ROLE FAILURE: an owner changed their own organization status';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('owner', 'cannot change the organization status');

  -- And creating a tenant is not theirs either.
  begin
    perform public.create_organization('owner-made-this', 'Owner Made This');
    raise exception 'ROLE FAILURE: an owner created an organization';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name)
  values ('owner', 'cannot create an organization');

  -- Writing the same value is not a change and must not be refused, or an
  -- ordinary rename would fail whenever the client sends the whole row back.
  update public.organizations
     set name = 'Renamed again', custom_integrations = custom_integrations
   where id = org;
  get diagnostics n = row_count;
  if n <> 1 then
    raise exception 'ROLE FAILURE: the guard blocked an update that changed nothing';
  end if;
  insert into public._role_results (acting_as, check_name)
  values ('owner', 'an unchanged flag does not block a rename');

  -- Owners may promote, which admins may not.
  update public.memberships set role = 'owner' where org_id = org and user_id = adminid;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: owner could not promote an admin to owner'; end if;
  insert into public._role_results (acting_as, check_name) values ('owner', 'promotes a member to owner');

  -- With two owners, standing down is allowed …
  update public.memberships set role = 'admin' where org_id = org and user_id = adminid;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'ROLE FAILURE: owner could not demote the second owner'; end if;
  insert into public._role_results (acting_as, check_name) values ('owner', 'demotes a second owner');

  -- … but the last owner cannot demote themselves out of the org.
  begin
    update public.memberships set role = 'admin'
    where org_id = org and user_id = '0a2a0000-0000-4000-8000-000000000001';
    raise exception 'ROLE FAILURE: the last owner demoted themselves';
  exception when restrict_violation then null;
  end;
  insert into public._role_results (acting_as, check_name) values ('owner', 'cannot demote the last owner');

  -- Self-removal is refused for every owner, not only the last one, and by the
  -- policy rather than the trigger — so the statement matches nothing instead
  -- of raising. Owners remove other owners; the last one leaves when the
  -- operations team closes the account.
  --
  -- The rule exists because removal now deletes the account behind it: without
  -- it, an owner destroys their own login by clicking the wrong row.
  delete from public.memberships
  where org_id = org and user_id = '0a2a0000-0000-4000-8000-000000000001';
  get diagnostics n = row_count;
  if n <> 0 then raise exception 'ROLE FAILURE: an owner removed their own membership'; end if;
  insert into public._role_results (acting_as, check_name) values ('owner', 'cannot remove themselves');

  -- The activity log is readable by the owner and writable by nobody. The
  -- absence of an insert grant is the whole of the tamper evidence, so it gets
  -- an assertion rather than a comment.
  begin
    insert into public.activity_log (org_id, action, subject)
    values (org, 'member.forged', 'not-a-real-event');
    raise exception 'ROLE FAILURE: an owner wrote to the activity log';
  exception when insufficient_privilege then null;
  end;
  insert into public._role_results (acting_as, check_name) values ('owner', 'cannot write the activity log');
end;
$$;

reset role;

insert into public._role_results (acting_as, check_name) values ('—', 'ALL CHECKS PASSED');

select n, acting_as, check_name, result from public._role_results order by n;

rollback;
