-- ============================================================================
-- The activity log
--
-- One table for both audiences. A row with an org_id is that organization's
-- business and its owner can read it; a row without one is platform business
-- and only operators can. Operators can read all of it, which is consistent
-- with the cross-tenant read they already hold everywhere else.
--
-- Two decisions worth stating, because both look like redundancy:
--
--   * The actor and the subject are stored as TEXT alongside their ids. A log
--     whose entries decay when the account they describe is deleted is not a
--     log — and deleting the account is one of the things being recorded here.
--     The ids are for joining while the rows still exist; the text is what
--     survives.
--
--   * There is no insert, update or delete policy, and `authenticated` is
--     granted SELECT only. Entries arrive through the service_role or through
--     SECURITY DEFINER functions, so nobody can forge an entry or quietly drop
--     one through the Data API — including the owner whose actions it records.
--     A log that its subject can edit is decoration.
--
-- Also here: an owner may not remove themselves. Owners remove other owners;
-- the last one leaves when the operations team closes the account. Without
-- this, "remove" plus "delete the account when it has no organizations left"
-- lets an owner destroy their own login by clicking the wrong row's button.
--
-- Additive and idempotent.
-- ============================================================================

create table if not exists public.activity_log (
  id           bigint generated by default as identity primary key,
  at           timestamptz not null default now(),
  --: Null for platform-level activity, which belongs to no tenant.
  org_id       uuid references public.organizations (id) on delete cascade,
  actor_id     uuid references auth.users (id) on delete set null,
  --: Denormalised on purpose — see the header.
  actor_email  text,
  action       text not null,
  subject      text,
  detail       jsonb not null default '{}'::jsonb
);

create index if not exists activity_log_org_at_idx on public.activity_log (org_id, at desc);
create index if not exists activity_log_at_idx     on public.activity_log (at desc);

comment on table public.activity_log is
  'Who did what, for an organization (org_id set) or for the platform (null). '
  'Append-only through the Data API: SELECT is granted, nothing else is.';

alter table public.activity_log enable row level security;

drop policy if exists "org owners read their own activity" on public.activity_log;
create policy "org owners read their own activity" on public.activity_log
  for select to authenticated
  using (org_id is not null and public.auth_is_org_owner(org_id));

drop policy if exists "platform admins read all activity" on public.activity_log;
create policy "platform admins read all activity" on public.activity_log
  for select to authenticated
  using (public.is_platform_admin());

-- SELECT and nothing else. The absence of an insert grant is the tamper
-- evidence, so it is deliberate rather than an oversight to be tidied up.
grant select on public.activity_log to authenticated;
grant select, insert on public.activity_log to service_role;

-- ------------------------------------------------- an owner is not self-removable
-- Enforced here rather than only in the Edge Function, so it holds whichever
-- route is taken. The cascade from delete_organization() is unaffected: a
-- cascade is not a policy-checked delete.
drop policy if exists "manage org memberships delete" on public.memberships;
create policy "manage org memberships delete" on public.memberships
  for delete to authenticated
  using (public.auth_is_org_owner(org_id) and user_id <> auth.uid());

-- ---------------------------------------------------------------- verify
-- A select, not a raise notice: the SQL editor discards notices. There should
-- be exactly two policies, both SELECT, and no write grant to authenticated.
select
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'activity_log')            as policies,
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'activity_log'
      and cmd <> 'SELECT')                                                 as non_select_policies,
  (select count(*) from information_schema.role_table_grants
    where table_schema = 'public' and table_name = 'activity_log'
      and grantee = 'authenticated' and privilege_type <> 'SELECT')        as authenticated_write_grants;
