-- ============================================================================
-- Multi-tenant Phase A4 — public endpoint hardening
--
-- Gives every printer an opaque, rotatable kiosk token (the thing the lobby QR
-- code encodes), adds per-org API keys for the external print API, and the
-- machinery for rate limits and queue caps — MULTI_TENANT_DESIGN.md §3.3, §3.4
-- and §7.
--
-- Additive and idempotent. The existing `?printer=<uuid>` links keep working;
-- nothing already printed and hanging in a lobby stops functioning.
-- ============================================================================

-- ------------------------------------------------------- 1. kiosk tokens

-- gen_random_uuid() rather than pgcrypto's gen_random_bytes(): it is built in,
-- uses the same strong RNG, and avoids depending on an extension being enabled.
-- 122 bits of randomness — not guessable, and short enough to keep the QR dense.
create or replace function public.new_kiosk_token()
returns text
language sql
volatile
as $$
  select 'k_' || replace(gen_random_uuid()::text, '-', '')
$$;

alter table public.printers
  add column if not exists kiosk_token text default public.new_kiosk_token();

-- Existing printers predate the column default.
update public.printers set kiosk_token = public.new_kiosk_token() where kiosk_token is null;

alter table public.printers alter column kiosk_token set not null;

create unique index if not exists printers_kiosk_token_key on public.printers (kiosk_token);

-- ------------------------------------------------------- 2. per-org API keys
-- Replaces the single project-wide PRINT_API_KEY secret with a credential that
-- resolves to one organization. Same shape as bridge_tokens: only the hash is
-- stored, the secret is shown once.

create table if not exists public.api_keys (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references public.organizations (id) on delete cascade,
  name         text,
  key_hash     text not null unique,
  key_prefix   text,
  last_used_at timestamptz,
  created_at   timestamptz not null default now(),
  revoked_at   timestamptz
);

create index if not exists api_keys_org_id_idx on public.api_keys (org_id);
create index if not exists api_keys_hash_idx   on public.api_keys (key_hash);

alter table public.api_keys enable row level security;

drop policy if exists "org read api_keys" on public.api_keys;
create policy "org read api_keys" on public.api_keys
  for select to authenticated using (public.auth_is_org_admin(org_id));

drop policy if exists "org insert api_keys" on public.api_keys;
create policy "org insert api_keys" on public.api_keys
  for insert to authenticated with check (public.auth_is_org_admin(org_id));

drop policy if exists "org update api_keys" on public.api_keys;
create policy "org update api_keys" on public.api_keys
  for update to authenticated
  using (public.auth_is_org_admin(org_id))
  with check (public.auth_is_org_admin(org_id));

drop policy if exists "org delete api_keys" on public.api_keys;
create policy "org delete api_keys" on public.api_keys
  for delete to authenticated using (public.auth_is_org_admin(org_id));

-- As with bridge_tokens: revoke first, because this project grants the Data API
-- roles full access to newly created tables.
revoke all on public.api_keys from anon, authenticated;
grant select (id, org_id, name, key_prefix, last_used_at, created_at, revoked_at)
  on public.api_keys to authenticated;
grant insert (org_id, name, key_hash, key_prefix) on public.api_keys to authenticated;
grant update (name, revoked_at) on public.api_keys to authenticated;
grant delete on public.api_keys to authenticated;

-- --------------------------------------------------- 3. rate-limit events
-- One row per public submission attempt, used for the rolling-window checks.
-- Nobody reads this through the Data API: it is written and read only by the
-- security-definer function below, which the Edge Functions call.

create table if not exists public.submit_events (
  id         bigint generated by default as identity primary key,
  org_id     uuid references public.organizations (id) on delete cascade,
  printer_id uuid references public.printers (id) on delete cascade,
  ip         text,
  at         timestamptz not null default now()
);

create index if not exists submit_events_printer_at_idx on public.submit_events (printer_id, at desc);
create index if not exists submit_events_ip_at_idx      on public.submit_events (ip, at desc);

alter table public.submit_events enable row level security;
-- Deliberately no policies: this table is invisible to every client role.
revoke all on public.submit_events from anon, authenticated;

-- ------------------------------------------------ 4. the gate itself
-- Records the attempt and returns NULL when it is allowed, or a message safe to
-- show a visitor when it is not. Doing this in one security-definer call keeps
-- it atomic and saves the Edge Function two round trips.
create or replace function public.check_submit_allowed(
  p_org             uuid,
  p_printer         uuid,
  p_ip              text,
  p_badges          int      default 1,
  p_max_per_ip      int      default 6,
  p_max_per_printer int      default 30,
  p_max_pending     int      default 40,
  p_window          interval default '1 minute'
)
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  n int;
begin
  -- Keep the table from growing without bound. Cheap: the index makes this a
  -- range delete, and it only ever touches rows nobody will read again.
  delete from public.submit_events where at < now() - interval '1 day';

  insert into public.submit_events (org_id, printer_id, ip, at)
  values (p_org, p_printer, p_ip, now());

  -- Per IP: catches one person or script hammering the form.
  if p_ip is not null then
    select count(*) into n
    from public.submit_events
    where ip = p_ip and at > now() - p_window;
    if n > p_max_per_ip then
      return 'Too many sign-ins from this device just now. Please wait a moment and try again.';
    end if;
  end if;

  -- Per printer: catches a distributed flood at one kiosk, and bounds the
  -- damage a leaked token can do to a single lobby.
  select count(*) into n
  from public.submit_events
  where printer_id = p_printer and at > now() - p_window;
  if n > p_max_per_printer then
    return 'This kiosk is busy right now. Please wait a moment and try again.';
  end if;

  -- Queue cap: never let the backlog grow past what the printer can clear.
  select count(*) into n
  from public.print_jobs
  where printer_id = p_printer and status in ('queued', 'printing');
  if n + p_badges > p_max_pending then
    return 'There are too many badges waiting to print. Please ask a greeter for help.';
  end if;

  return null;
end;
$$;

-- Only the Edge Functions may call it. Postgres grants EXECUTE to PUBLIC by
-- default, so revoking from anon/authenticated alone would leave that in place —
-- it has to come off PUBLIC and be granted back explicitly.
revoke all on function public.check_submit_allowed(uuid, uuid, text, int, int, int, int, interval)
  from public;
grant execute on function public.check_submit_allowed(uuid, uuid, text, int, int, int, int, interval)
  to service_role;
